{% set name = "prophet" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e682e8ea6e1ee26a92cf289f207d539f30e44879126c128ff8f4e360eb25a8b

build:
  number: 4
  skip: true  # [win and py<37]
  script: "{{ PYTHON }} -m pip install . -vv"
  binary_has_prefix_files:
    - {{ SP_DIR|replace("\\", "/") }}/stan_model/prophet_model.pkl

requirements:
  host:
    - python
    - pip
    # Explanation:
    #
    # setup.py imports fbprophet.models.StanBackendEnum, triggering
    # fbprophet/__init__.py and thus making the runtime dependencies
    # also build-time dependencies.
    #
    # These requirements are copied from python/requirements.txt
    - cython >=0.22
    - cmdstanpy ==0.9.68
    - pystan ~=2.19.1.1
    - numpy >=1.15.4
    - pandas >=1.0.4
    - matplotlib-base >=2.0.0
    - LunarCalendar >=0.0.9
    - convertdate >=2.1.2
    - holidays >=0.10.2
    - setuptools-git >=1.2
    - python-dateutil >=2.8.0
    - tqdm >=4.36.1
  run:
    - python
    - cython >=0.22
    - cmdstanpy ==0.9.68
    - pystan ~=2.19.1.1
    - pandas >=1.0.4
    - matplotlib-base >=2.0.0
    - LunarCalendar >=0.0.9
    - convertdate >=2.1.2
    - holidays >=0.10.2
    - setuptools-git >=1.2
    - python-dateutil >=2.8.0
    - tqdm >=4.36.1
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - prophet
    - prophet.tests
  commands:
    - pip check
    - py.test -v --pyargs prophet
  requires:
    - pip
    - pytest

about:
  home: https://facebook.github.io/prophet/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Automatic Forecasting Procedure
  description: |
    Implements a procedure for forecasting time series data based on an
    additive model where non-linear trends are fit with yearly, weekly, and
    daily seasonality, plus holiday effects. It works best with time series
    that have strong seasonal effects and several seasons of historical data.
    Prophet is robust to missing data and shifts in the trend, and typically
    handles outliers well.
  doc_url: https://facebook.github.io/prophet/docs/quick_start.html
  dev_url: https://github.com/facebook/prophet

extra:
  recipe-maintainers:
    - bletham
